variable "resource_id" {
  description = "(Required) The ID of the resource on which activate the diagnostic settings."
  type        = string
  nullable    = false
}
variable "log_categories" {
  description = "(Optional) List of log categories. Defaults to all available."
  type        = list(string)
  default     = [null]
}
variable "excluded_log_categories" {
  description = "(Optional) List of log categories to exclude."
  type        = list(string)
  default     = [null]
}
variable "metric_categories" {
  description = "(Optional) List of metric categories. Defaults to all available."
  type        = list(string)
  default     = null
}
variable "logs_destinations_ids" {
  description = "(Optional) Provide the Resource ID of a Storage Account, Log Analytics Workspace or EventHub, you can include multiple destinations in a string list."
  type        = list(string)
  nullable    = false
}
variable "log_analytics_destination_type" {
  description = "(Optional) Set the Log Analytics storage to use the built-in AzureDiagnostics table or create dedicated tables for this resource. Defaults to `AzureDiagnostics`."
  type        = string
  default     = "AzureDiagnostics"

  validation {
    condition     = can(regex("^AzureDiagnostics|Dedicated$", var.log_analytics_destination_type))
    error_message = "Invalid log analytics destination type. Accepted values are 'AzureDiagnostics' or 'Dedicated'."
  }
}
variable "name_prefix" {
  description = "(Optional) Prefix for the generated name."
  type        = string
  default     = ""
}
variable "name_suffix" {
  description = "(Optional) Suffix for the generated name."
  type        = string
  default     = ""
}
variable "use_caf_naming" {
  description = "(Optional) Use the Azure CAF naming provider to generate default resource name. `custom_name` override this if set. Legacy default name is used if this is set to `false`. Defaults to `true`."
  type        = bool
  default     = true
}
variable "custom_name" {
  description = "(Optional) Name of the diagnostic settings. If none provided this will be generated by the data blocks for AzureCAF. Defaults to `Null`."
  type        = string
  default     = null
}
