parameters:
  - name: connectedServiceName
    type: string

steps:         
- task: TerraformInstaller@0
  displayName: Terraform Installer
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  name: exported_azure_credentials
  displayName: 'Import Service Principal Credentials'
  inputs:
    azureSubscription: '${{ parameters.connectedServiceName }}'
    scriptType: pscore
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    inlineScript: |
      $subscriptionName = $env:SUBSCRIPTIONNAME
      $subscriptionId = convertfrom-json (az account list --query "[?isDefault].id | [0]")

      Write-Host "##vso[task.setvariable variable=AZURE_TENANT_ID]$env:tenantId"
      Write-Host "##vso[task.setvariable variable=AZURE_TENANT_ID;isOutput=true]$env:tenantId"
      Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_ID]$env:servicePrincipalId"
      Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_ID;isOutput=true]$env:servicePrincipalId"
      Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_SECRET]$env:servicePrincipalKey"
      Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_SECRET;isOutput=true]$env:servicePrincipalKey"
      Write-Host "##vso[task.setvariable variable=AZURE_SUBSCRIPTION_ID]$subscriptionId"
      Write-Host "##vso[task.setvariable variable=AZURE_SUBSCRIPTION_ID;isOutput=true]$subscriptionId"
